(function() {var implementors = {};
implementors["peresil"] = ["impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='peresil/struct.StringPoint.html' title='peresil::StringPoint'>StringPoint</a>&lt;'a&gt;",];implementors["sxd_document"] = ["impl&lt;'d&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='sxd_document/dom/struct.Root.html' title='sxd_document::dom::Root'>Root</a>&lt;'d&gt;","impl&lt;'d&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='sxd_document/dom/struct.Element.html' title='sxd_document::dom::Element'>Element</a>&lt;'d&gt;","impl&lt;'d&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='sxd_document/dom/struct.Attribute.html' title='sxd_document::dom::Attribute'>Attribute</a>&lt;'d&gt;","impl&lt;'d&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='sxd_document/dom/struct.Text.html' title='sxd_document::dom::Text'>Text</a>&lt;'d&gt;","impl&lt;'d&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='sxd_document/dom/struct.Comment.html' title='sxd_document::dom::Comment'>Comment</a>&lt;'d&gt;","impl&lt;'d&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='sxd_document/dom/struct.ProcessingInstruction.html' title='sxd_document::dom::ProcessingInstruction'>ProcessingInstruction</a>&lt;'d&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='enum' href='sxd_document/parser/enum.Error.html' title='sxd_document::parser::Error'>Error</a>","impl&lt;'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Eq.html' title='core::cmp::Eq'>Eq</a> for <a class='struct' href='sxd_document/struct.PrefixedName.html' title='sxd_document::PrefixedName'>PrefixedName</a>&lt;'a&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
